# Hugo Blox GitHub Action to import Jupyter Notebooks as blog mls
name: Import Jupyter Notebooks as Blog ml

# Require permission to create a PR
permissions:
  contents: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated in the `data/` folder
on:
  push:
    branches: ['main']
    paths: ['notebooks/*.ipynb']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.11.2
      - name: Run Academic Converter Tool
        run: academic import 'notebooks/*.ipynb' content/ml/ --verbose
      - name: Create Pull Request
        # Set ID for `Check outputs` stage
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'content: import blog ML from `notebooks/` folder'
          title: Hugo Blox Builder - Import latest blog ML
          body: |
            Convert Jupyter Notebooks in the `notebooks/` folder into blog ML in the `content/ml/` folder.
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-ml
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
